name: Astra-dev-environment-start-stop -testing
on:
  push:
    #branches: [ dev ] 
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "Checking out repository "

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Execute my python script for job - Start
        run: |
            ECRACCOUNTID=$(aws sts get-caller-identity --query Account --output text)
            echo ${ECRACCOUNTID}
            python test.py start

      - name: Execute my python script for job - Stop
        run: |
            ECRACCOUNTID=$(aws sts get-caller-identity --query Account --output text)
            echo ${ECRACCOUNTID}
            python test.py stop

      - name: Execute my python script for job - Status
        run: |
            ECRACCOUNTID=$(aws sts get-caller-identity --query Account --output text)
            echo ${ECRACCOUNTID}
            python test.py status