name: Testing
on: [push]

jobs:
  Testing:
    runs-on: ubuntu-latest
#    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_SECRET_ACCESS_KEY_IAM: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAM }}
      AWS_SESSION_TOKEN_IAM: ${{ secrets.AWS_SESSION_TOKEN_IAM }}
      AWS_ECRACCOUNTID: ${{secrets.AWS_ECRACCOUNTID}}

    steps:  
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: echo "Checking out repository "

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test Docker login
        if: ${{ always() }}
        run: |
          ECRACCOUNTID=$(aws sts get-caller-identity --query Account --output text)
          echo ${ECRACCOUNTID}
      
      - name: Login to ECR
        if: ${{ always() }}
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.AWS_ECRACCOUNTID}}.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID_IAM }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY_IAM }}
        env: 
          ECRACCOUNTID : $(aws sts get-caller-identity --query Account --output text)